//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbTradekeralaEntities1 : DbContext
    {
        public DbTradekeralaEntities1()
            : base("name=DbTradekeralaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_RelatedProducts> tbl_RelatedProducts { get; set; }
        public virtual DbSet<tbl_specialoffer> tbl_specialoffer { get; set; }
        public virtual DbSet<tbl_trendingProducts> tbl_trendingProducts { get; set; }
        public virtual DbSet<tbl_wishlist> tbl_wishlist { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblfavorite> tblfavorites { get; set; }
        public virtual DbSet<tblProdImage> tblProdImages { get; set; }
        public virtual DbSet<tblSale> tblSales { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tbl_ProductOffer> tbl_ProductOffer { get; set; }
        public virtual DbSet<tbl_TodaysDeal> tbl_TodaysDeal { get; set; }
        public virtual DbSet<tb_TopCategory> tb_TopCategory { get; set; }
        public virtual DbSet<Vw_TodaysDeals> Vw_TodaysDeals { get; set; }
        public virtual DbSet<Vw_DealsOffer> Vw_DealsOffer { get; set; }
        public virtual DbSet<tb_TopBrand> tb_TopBrand { get; set; }
        public virtual DbSet<tblNewsletter> tblNewsletters { get; set; }
        public virtual DbSet<tbl_Banner> tbl_Banner { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tbl_PreBooking> tbl_PreBooking { get; set; }
        public virtual DbSet<tbl_JobSeeker> tbl_JobSeeker { get; set; }
        public virtual DbSet<tbl_Job> tbl_Job { get; set; }
        public virtual DbSet<tbl_SellerImage> tbl_SellerImage { get; set; }
        public virtual DbSet<tblRecentView> tblRecentView { get; set; }
        public virtual DbSet<tbl_Notfication> tbl_Notfication { get; set; }
        public virtual DbSet<tbl_Organic> tbl_Organic { get; set; }
        public virtual DbSet<tbl_Logistics> tbl_Logistics { get; set; }
        public virtual DbSet<tbl_Pincode> tbl_Pincode { get; set; }
        public virtual DbSet<tbl_HidedProducts> tbl_HidedProducts { get; set; }
        public virtual DbSet<tbl_HiddenImage> tbl_HiddenImage { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tbl_Vendor> tbl_Vendor { get; set; }
        public virtual DbSet<tblRegistration> tblRegistration { get; set; }
        public virtual DbSet<tblreviews> tblreviews { get; set; }
        public virtual DbSet<tbl_cart> tbl_cart { get; set; }
        public virtual DbSet<tb_address> tb_address { get; set; }
        public virtual DbSet<tblOrders> tblOrders { get; set; }
        public virtual DbSet<tbl_BulkOrder> tbl_BulkOrder { get; set; }
    
        public virtual ObjectResult<Relatedpro_Result> Relatedpro(string catid)
        {
            var catidParameter = catid != null ?
                new ObjectParameter("catid", catid) :
                new ObjectParameter("catid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Relatedpro_Result>("Relatedpro", catidParameter);
        }
    
        public virtual ObjectResult<sp_autocomplete_Result> sp_autocomplete(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_autocomplete_Result>("sp_autocomplete", keywordParameter);
        }
    
        public virtual ObjectResult<sp_Catautocomplete_Result> sp_Catautocomplete(string catkeyword, string catWord)
        {
            var catkeywordParameter = catkeyword != null ?
                new ObjectParameter("Catkeyword", catkeyword) :
                new ObjectParameter("Catkeyword", typeof(string));
    
            var catWordParameter = catWord != null ?
                new ObjectParameter("CatWord", catWord) :
                new ObjectParameter("CatWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Catautocomplete_Result>("sp_Catautocomplete", catkeywordParameter, catWordParameter);
        }
    
        public virtual ObjectResult<Sp_GetOffers_Result> Sp_GetOffers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetOffers_Result>("Sp_GetOffers");
        }
    
        public virtual ObjectResult<sp_newproducts_Result> sp_newproducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_newproducts_Result>("sp_newproducts");
        }
    
        public virtual ObjectResult<sp_Offer_Result> sp_Offer(string offerName, string min, string max, string color, string wt, string sz)
        {
            var offerNameParameter = offerName != null ?
                new ObjectParameter("OfferName", offerName) :
                new ObjectParameter("OfferName", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Offer_Result>("sp_Offer", offerNameParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter);
        }
    
        public virtual int sp_searchdummy(string property_name, string cat_name)
        {
            var property_nameParameter = property_name != null ?
                new ObjectParameter("Property_name", property_name) :
                new ObjectParameter("Property_name", typeof(string));
    
            var cat_nameParameter = cat_name != null ?
                new ObjectParameter("cat_name", cat_name) :
                new ObjectParameter("cat_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_searchdummy", property_nameParameter, cat_nameParameter);
        }
    
        public virtual ObjectResult<sp_Trending_Result> sp_Trending()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Trending_Result>("sp_Trending");
        }
    
        public virtual int sp_TrendAdd(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TrendAdd", iDParameter);
        }
    
        public virtual ObjectResult<sp_TrendPro_Result> sp_TrendPro(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TrendPro_Result>("sp_TrendPro", iDParameter);
        }
    
        public virtual int sp_search_products(string property_name, string cat_name, string min, string max, string color, string wt, string sz, string br, Nullable<int> pageNo, Nullable<int> rowsPerPage)
        {
            var property_nameParameter = property_name != null ?
                new ObjectParameter("Property_name", property_name) :
                new ObjectParameter("Property_name", typeof(string));
    
            var cat_nameParameter = cat_name != null ?
                new ObjectParameter("cat_name", cat_name) :
                new ObjectParameter("cat_name", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_search_products", property_nameParameter, cat_nameParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter, pageNoParameter, rowsPerPageParameter);
        }
    
        public virtual int sp_search_productspaging(string property_name, string cat_name, string min, string max, string color, string wt, string sz, string br)
        {
            var property_nameParameter = property_name != null ?
                new ObjectParameter("Property_name", property_name) :
                new ObjectParameter("Property_name", typeof(string));
    
            var cat_nameParameter = cat_name != null ?
                new ObjectParameter("cat_name", cat_name) :
                new ObjectParameter("cat_name", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_search_productspaging", property_nameParameter, cat_nameParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter);
        }
    
        public virtual ObjectResult<Vw_TodaysDeals> sp_Search_Today(string offerName, string diMin, string diMax, string min, string max, string color, string wt, string sz, string br, Nullable<int> pageNo, Nullable<int> rowsPerPage)
        {
            var offerNameParameter = offerName != null ?
                new ObjectParameter("OfferName", offerName) :
                new ObjectParameter("OfferName", typeof(string));
    
            var diMinParameter = diMin != null ?
                new ObjectParameter("diMin", diMin) :
                new ObjectParameter("diMin", typeof(string));
    
            var diMaxParameter = diMax != null ?
                new ObjectParameter("diMax", diMax) :
                new ObjectParameter("diMax", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vw_TodaysDeals>("sp_Search_Today", offerNameParameter, diMinParameter, diMaxParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter, pageNoParameter, rowsPerPageParameter);
        }
    
        public virtual ObjectResult<Vw_TodaysDeals> sp_Search_Today(string offerName, string diMin, string diMax, string min, string max, string color, string wt, string sz, string br, Nullable<int> pageNo, Nullable<int> rowsPerPage, MergeOption mergeOption)
        {
            var offerNameParameter = offerName != null ?
                new ObjectParameter("OfferName", offerName) :
                new ObjectParameter("OfferName", typeof(string));
    
            var diMinParameter = diMin != null ?
                new ObjectParameter("diMin", diMin) :
                new ObjectParameter("diMin", typeof(string));
    
            var diMaxParameter = diMax != null ?
                new ObjectParameter("diMax", diMax) :
                new ObjectParameter("diMax", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vw_TodaysDeals>("sp_Search_Today", mergeOption, offerNameParameter, diMinParameter, diMaxParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter, pageNoParameter, rowsPerPageParameter);
        }
    
        public virtual ObjectResult<Vw_DealsOffer> sp_Search_Deals(string offerName, string diMin, string diMax, string min, string max, string color, string wt, string sz, string br, Nullable<int> pageNo, Nullable<int> rowsPerPage)
        {
            var offerNameParameter = offerName != null ?
                new ObjectParameter("OfferName", offerName) :
                new ObjectParameter("OfferName", typeof(string));
    
            var diMinParameter = diMin != null ?
                new ObjectParameter("diMin", diMin) :
                new ObjectParameter("diMin", typeof(string));
    
            var diMaxParameter = diMax != null ?
                new ObjectParameter("diMax", diMax) :
                new ObjectParameter("diMax", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vw_DealsOffer>("sp_Search_Deals", offerNameParameter, diMinParameter, diMaxParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter, pageNoParameter, rowsPerPageParameter);
        }
    
        public virtual ObjectResult<Vw_DealsOffer> sp_Search_Deals(string offerName, string diMin, string diMax, string min, string max, string color, string wt, string sz, string br, Nullable<int> pageNo, Nullable<int> rowsPerPage, MergeOption mergeOption)
        {
            var offerNameParameter = offerName != null ?
                new ObjectParameter("OfferName", offerName) :
                new ObjectParameter("OfferName", typeof(string));
    
            var diMinParameter = diMin != null ?
                new ObjectParameter("diMin", diMin) :
                new ObjectParameter("diMin", typeof(string));
    
            var diMaxParameter = diMax != null ?
                new ObjectParameter("diMax", diMax) :
                new ObjectParameter("diMax", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var wtParameter = wt != null ?
                new ObjectParameter("Wt", wt) :
                new ObjectParameter("Wt", typeof(string));
    
            var szParameter = sz != null ?
                new ObjectParameter("sz", sz) :
                new ObjectParameter("sz", typeof(string));
    
            var brParameter = br != null ?
                new ObjectParameter("Br", br) :
                new ObjectParameter("Br", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vw_DealsOffer>("sp_Search_Deals", mergeOption, offerNameParameter, diMinParameter, diMaxParameter, minParameter, maxParameter, colorParameter, wtParameter, szParameter, brParameter, pageNoParameter, rowsPerPageParameter);
        }
    }
}
