//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_address
    {
        public int ID { get; set; }
        public string user_Id { get; set; }
        public string fullname { get; set; }
        public string Address { get; set; }
        public Nullable<long> Phone { get; set; }
        public Nullable<long> pincode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}
