//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Banner
    {
        public int Banner_id { get; set; }
        public string BannerName { get; set; }
        public string Related_To { get; set; }
        public string BannerImage { get; set; }
        public string Status { get; set; }
    }
}
