//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Logistics
    {
        public int Logistic_Id { get; set; }
        public string Log_Name { get; set; }
        public string weight { get; set; }
        public string category_One { get; set; }
        public string category_Two { get; set; }
        public string category_Three { get; set; }
        public string category_Four { get; set; }
        public string category_Five { get; set; }
    }
}
