//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RelatedProducts
    {
        public int Id { get; set; }
        public Nullable<int> Prodct_Id { get; set; }
        public string prodct_Name { get; set; }
        public Nullable<int> Related_Id { get; set; }
        public string Related_Product { get; set; }
    }
}
