//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job
    {
        public int Job_Id { get; set; }
        public string Job_Name { get; set; }
        public string job_Category { get; set; }
        public string Job_Description { get; set; }
        public string key_skills { get; set; }
        public string Experience { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> Posted_date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}
