//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobSeeker
    {
        public int Seeker_Id { get; set; }
        public string Seerker_Name { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Job_Applied { get; set; }
        public string Resume { get; set; }
    }
}
