//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendor
    {
        public int Vendor_id { get; set; }
        public string Vendor_Name { get; set; }
        public string Address { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<long> LandLine { get; set; }
        public string Pro_Image { get; set; }
        public string Pro_Info { get; set; }
        public string Pincode { get; set; }
        public string state { get; set; }
        public string Status { get; set; }
        public string SignIn { get; set; }
    }
}
