//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pincode
    {
        public int Post_id { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Place { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Taluk { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
