//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrand
    {
        public int Brandid { get; set; }
        public string BrandName { get; set; }
        public string BrandLogo { get; set; }
        public string BrandDesc { get; set; }
    }
}
