//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrders
    {
        public int Orderno { get; set; }
        public string Invoice_Id { get; set; }
        public string Userid { get; set; }
        public Nullable<int> ProId { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> Vendor { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Discount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public string Tax { get; set; }
        public Nullable<int> Address { get; set; }
        public string Gift { get; set; }
        public string DeliveryMethod { get; set; }
        public string PaymentMethod { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderTime { get; set; }
    }
}
