//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int id { get; set; }
        public string RegName { get; set; }
        public string RegEmail { get; set; }
        public string RegPassword { get; set; }
        public string RegMobile { get; set; }
        public string status { get; set; }
        public string type { get; set; }
    }
}
