//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreviews
    {
        public int id { get; set; }
        public Nullable<int> prodid { get; set; }
        public Nullable<int> starValue { get; set; }
        public string date { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string reviews { get; set; }
        public string type { get; set; }
    }
}
