//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeKerala2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int id { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<decimal> Oldprice { get; set; }
        public Nullable<decimal> Newprice { get; set; }
    }
}
